### ISSUE TITLE
之前的那个数组去重，

### ISSUE THREAD

**Issue by wxx2258** [gdutrdc-frontend/xbwwwww#1]
如果是[0,1,2,3,'1','2','3',1,2,3]，前面加个判断，判断是否类型，然后根据什么类型，后面加段标记字符串，就可以解决了。
在网上看到的
var uniqArray4 = function(arr) {
    var result = [];
    var hash = {};  
    var item,key;
    for(var i = 0, arrLen = arr.length; i < arrLen; i++) {
        item = arr[i];
        //对象的键值只能是字符串，
        key = typeof(item) + item;   //区分数值 1 和字符串 '1' 等情况
        if(!hash[key]) {  
              result.push(item);  //hash用来反射key是否重复
              hash[key] = true;   //表明该值存进新数组了
        }
    }
    return result;
};

**Comment by rbinnn** [comment]
那么问题又来了，如果我的数组是这样的呢？

```
var arr = [
  {
   name : "1"
  },
 {
   name : "1"
 },
 {
   name : 1
 },
 {
   name : 1,
   next : {
     name : '1'
   }
 },
 1,
 '1'
]
```

**Comment by rbinnn** [comment]
即是数组中的元素不再是是单纯的原始值，而是对象呢？
这道题其实是昨天去微信做的其中一道笔试题

**Comment by wxx2258** [comment]
在网上看到一种，JSON.string

Array.prototype.getUnique = function() {
        var hash = {}, result = [], key; 
        for ( var i = 0, l = this.length; i < l; ++i ) {
            key = JSON.stringify(this[i]);
            if ( !hash.hasOwnProperty(key) ) {
                hash[key] = true;
                result.push(this[i]);
            }
        }
        return result;
    };

**Comment by wxx2258** [comment]
```
Array.prototype.getUnique = function() { `
        var hash = {}, result = [], key; 
        for ( var i = 0, l = this.length; i < l; ++i ) {
            key = JSON.stringify(this[i]);
            if ( !hash.hasOwnProperty(key) ) {
                hash[key] = true;
                result.push(this[i]);
            }
        }
        return result;
    }; 
```

**Comment by wxx2258** [comment]
JSON.stringiify()方法可以区分数组和字符，同时也可以区分对象
JSON.stringify("1") === JSON.stringify(1)
JSON.stringify({name:1}) === JSON.stringify({name:"1"})

字符化后的代码同样同理之前

**Comment by rbinnn** [comment]
对的，就是这样，所以用JSON.stringify是最好的方法

**Comment by xxxBW** [comment]
谢谢小滨滨指教~
